version: '3'

networks:
  student-sphere:
volumes:
  logs:
  db_volume:

services:
  outreach-db:
    image: mysql:8.0.23
    restart: always
    networks:
      - student-sphere
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: anshul98
    volumes:
      - db_volume:/var/lib/mysql

  backend-spring:
    image: anshulsankhyan98/spe_major_project_backend:latest
    restart: always
    networks:
      - student-sphere
    environment:
      DATABASE_HOST: outreach-db
    ports:
      - "8082:8082"
    volumes:
      - logs:/logs

  frontend-react:
    image: anshulsankhyan98/spe_major_project_frontend:latest
    restart: always
    ports:
      - "3000:3000"
