version: '3'

networks:
  student-sphere:
    driver: bridge
volumes:
  logs:
  db_volume:

services:
  outreach-db:
    image: mysql:8.0.23
    restart: always
    healthcheck:
        test: ["CMD","ls"]
    networks:
      - student-sphere
    environment:
      MYSQL_ROOT_PASSWORD: anshul98
      MYSQL_DATABASE: student_sphere
    volumes:
      - db_volume:/var/lib/mysql

  backend-spring:
    image: anshulsankhyan98/spe_major_project_backend:latest
    restart: always
    depends_on:
      outreach-db:
        condition: service_healthy
    networks:
      - student-sphere
    environment:
      DATABASE_HOST: outreach-db
    ports:
      - "8082:8082"
    volumes:
      - logs:/logs

  frontend-react:
    image: anshulsankhyan98/spe_major_project_frontend:latest
