---
- name: Docker Pull and Run
  hosts: all
  remote_user: root
  become: true
  tasks:
    - name: Install aptitude using apt
      apt:
        name: aptitude
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Install required system packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common','python3', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        update_cache: yes
        name: docker-ce
        state: latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Docker pull mysql
      docker_image:
        name: mysql:8.0.33
        source: pull

    - name: Create Docker Network
      docker_network:
        name: student-sphere

    - name: Remove react existing container
      docker_container:
        name: spe_major_project_frontend
        state: absent

    - name: Remove spring existing container
      docker_container:
        name: spe_major_project_backend
        state: absent

    - name: Remove react existing image for fresh pull
      docker_image:
        name: anshulsankhyan98/spe_major_project_frontend:latest
        state: absent

    - name: Remove spring existing image for fresh pull
      docker_image:
        name: anshulsankhyan98/spe_major_project_backend:latest:latest
        state: absent

    - name: Docker pull React-app
      docker_image:
        name: anshulsankhyan98/spe_major_project_frontend:latest
        source: pull

    - name: Docker pull Spring-app
      docker_image:
        name: anshulsankhyan98/spe_major_project_backend:latest
        source: pull

    - name: Remove mysql existing container
      docker_container:
        name: outreach-db
        state: absent

    - name: Create MYSQL container
      docker_container:
        name: outreach-db
        image: mysql:8.0.23
        networks:
          - name: "student-sphere"
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: Anshul98#
        ports:
          - "3307:3306"

    - name: Remove existing log folder
      command: sudo rm -rf log-info

    - name: Create outreach-spring container
      docker_container:
        name: backend-spring
        image: anshulsankhyan98/spe_major_project_backend:latest
        networks:
          - name: "student-sphere"
        env:
          DATABASE_HOST: root
        ports:
          - "8082:8082"
        volumes:
          -
