---
- name: Docker Pull and Run
  hosts: all
  remote_user: root
  become: true
  tasks:
    - name: Install Docker
      shell: apt-get update && apt-get install docker.io
      
    - name: Install Docker-compose
      shell: apt-get docker-compose
      
    - name: copy docker-compose file
      copy:
        src: ./docker-compose.yml
        dest: ./
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: remove containers using docker-compose
      command: docker-compose down       

    - name: Create containers using docker-compose
      command: docker-compose up -d
      
        
