---
- name: Docker Pull and Run
  hosts: all
  remote_user: root
  become: true
  tasks:
    - name: Install aptitude using apt
      apt:
        name: aptitude
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Install required system packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common','python3', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        update_cache: yes
        name: docker-ce
        state: latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Remove existing containers and images
      docker_container:
        name:
          - spe_major_project_frontend
          - spe_major_project_backend
          - outreach-db
        state: absent
      docker_image:
        name:
          - anshulsankhyan98/spe_major_project_frontend:latest
          - anshulsankhyan98/spe_major_project_backend:latest
        state: absent

    - name: Pull Docker images
      docker_image:
        name:
          - mysql:8.0.33
          - anshulsankhyan98/spe_major_project_frontend:latest
          - anshulsankhyan98/spe_major_project_backend:latest
        source: pull

    - name: Create Docker Network
      docker_network:
        name: student-sphere

    - name: Create containers using docker-compose
      command: docker-compose up -d
      
        
